version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "singp191"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-615syr5c19ow"
s3_prefix = "singp191"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
