AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Tags:
      PrimaryOwner: "christopher.wheaton@pfizer.com"
      SecondaryOwner: "dimosthenis.chatzopoulos@pfizer.com"
      CostCenterID: "2320613"
Resources:
  CUSPFEsample:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - 's3:GetObject'
              Resource: 'arn:aws:s3::*'
      Events:
        CUSPFEsampleEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*

  SrcBucket:
    Type: AWS::S3::Bucket